config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :markets, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  def index
    @facade = MarketsFacade.new
  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketMoneyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<style>
  h1 {
    text-align: center;
  }
  th {
    text-align: center;
  }
  td {
    text-align: center;
  }
</style>

<h1> Markets </h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>State</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @facade.market_index.each do |market| %>
      <div id="market<%= market.market_id %>">
        <tr>
          <td><%= market.name %></td>
          <td><%= market.city %></td>
          <td><%= market.state %></td>
          <td><%= button_to "More Info", market_path(market.market_id), method: :get, data: { turbo: false } %></td>
        </tr>
      </div>
    <% end %>
  </tbody>
</table>